### ISSUE TITLE
how to populate IR_*_clone_id columns?

### ISSUE THREAD

**Issue by zktuong** [icbi-lab/scirpy#258]
Hi @grst, I can't work out when in the analysis workflow is the `IR_*_clone_id` columns populated. Toggling `dual_ir` option doesn't seem to change that behaviour. Does it actually get populated from preprocessing/analysis performed within scirpy?

**Comment by grst** [comment]
No, these columns would actually only get populated when reading in the
`clone_id` column from an AIRR formatted file and not flagging `clone_id`
as a cell-level attribute.
(Cell-level attributes must be the same in all records belonging to a cell
in the AIRR table, and would then only get a single column in `adata.obs`
instead of one for each chain.

But this behavior is still pretty much in the works.

Clonotype assignments called with scirpy are stored in a single `clonotype`
column, or `cc_{sequence}_{metric}` for "clonotype clusters".

**Comment by grst** [comment]
The more I think about it: probably it's best to just use `clone_id` as the default output column for `define_clonotypes`.
